
export const messageIdeas = [
  "What goals have you accomplished since writing this message?",
  "What would your past self be surprised to learn about your life now?",
  "What advice would you give to your past self based on what you know now?",
  "What dreams are you still chasing? Which ones have you let go of?",
  "What's the most important lesson you've learned since writing this?",
  "What are you grateful for today that you weren't when you wrote this?",
  "How have your priorities changed since sending this message?",
  "What do you wish you had started doing earlier in life?",
  "What habits have shaped your life for better or worse?",
  "What relationships have had the biggest impact on your life?",
  "What fears have you overcome? What fears still hold you back?",
  "What's something you're proud of that nobody knows about?",
  "What adventures have you had since writing this message?",
  "How have you grown emotionally and mentally since this message?",
  "What's the biggest risk you've taken? Was it worth it?",
  "If you could talk to your past self, what would you say?",
  "What is your definition of success now? Has it changed?",
  "What brings you joy today that you didn't expect?",
  "What have you learned to let go of?",
  "What's something you know now that you wish you knew back then?",
  "How have you surprised yourself since writing this?",
  "What challenges have you overcome that you never thought possible?",
  "What are you looking forward to in the next chapter of your life?",
  "What legacy do you hope to leave behind?",
  "How have your beliefs about yourself evolved?",
  "What secret dreams are you nurturing now?",
  "How has your worldview changed since writing this?",
  "What's the most valuable use of your time now?",
  "What would make future-you proud?",
  "What's something you've forgiven yourself for?",
  "How have the hardest moments shaped who you are now?",
  "What's a truth you've discovered about yourself?",
  "What do you hope never changes about your life?",
  "What talents or interests have you discovered or rediscovered?",
  "How have your relationships evolved over time?",
  "What makes life meaningful to you now?",
  "What's your relationship with your body like now?",
  "What have you learned about love since writing this?",
  "What are you still curious about?",
  "How do you define 'home' now?",
];
